export type ObservedUsage = {
  source: string;
  scope: 'manager_total' | 'reference';
  up: number | null;
  down: number | null;
  limit: number | null;
  expire_at: number | null;
  collected_at: number;
};
export type ObservedInbound = {
  id: string;
  tag: string;
  protocol: string;
  listen: string;
  port: string;
  transport: string;
  tls: boolean;
  reality: boolean;
  users: number | null;
  enabled: boolean | null;
  in_config: boolean;
  listening: boolean | null;
  usage: ObservedUsage | null;
};
export type ObservedInstance = {
  id: string;
  core: 'sing-box' | 'xray';
  source: string;
  ownership: 'managed' | 'external';
  version: string;
  running: boolean;
  pid: number;
  process_start: string;
  manager_pid: number;
  manager_running: boolean | null;
  service: string;
  binary: string;
  config_paths: string[];
  namespace: string;
  rss_bytes: number | null;
  ports: { address: string; port: number; network: string }[];
  inbounds: ObservedInbound[];
  stats_status: string;
  issues: string[];
  config_read_at: number;
  last_success: number;
  received_at: number;
  stale: boolean;
  absent: boolean;
  truncated: boolean;
};
export type ProxyObservations = {
  management: 'managed' | 'external' | 'none' | 'unknown';
  online: boolean;
  supported: boolean;
  instances: ObservedInstance[];
};
